- hosts: all
  become: yes
  user: vagrant
  tasks:
    - name: atom ppa added.
      apt_repository: repo='ppa:webupd8team/atom'
    - name: atom installed.
      package: name='atom' state='latest'
